# frozen_string_literal: true

require 'minitest/autorun'
require 'algorithm_x'
require 'sudoku_matrix'

class SudokuMatrixTest < Minitest::Test
  def test_display
    assert_equal <<~STR.strip, SudokuMatrix.to_string
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........
    STR
  end

  def test_adding_clues_then_solving
    matrix = SudokuMatrix.new
    matrix.add_clue(row: 2, col: 5, digit: 9)
    matrix.add_clue(row: 7, col: 2, digit: 4)
    assert_equal <<~STR.strip, SudokuMatrix.to_string(positions: matrix.clues)
      .........
      .........
      .....9...
      .........
      .........
      .........
      .........
      ..4......
      .........
    STR
    positions = AlgorithmX.new(matrix).solve
    assert_equal matrix.clues, matrix.clues & positions
  end

  def test_can_be_solved_by_algorithm_x
    positions = AlgorithmX.new(SudokuMatrix.new).solve
    assert positions.size == 81
    assert_equal <<~STR.strip, SudokuMatrix.to_string(positions: positions)
      123456789
      467189235
      589237164
      218365947
      374918652
      695724318
      731542896
      842691573
      956873421
    STR
  end
end
